### PR TITLE
Setup overview fe

### PR DESCRIPTION
**Pull request by beasterbro**
adding list view of schedule which displays assignment and tasks, sections should be on the way

### CODE REVIEW

**Comment by lucaspopp0** [comment]
Why not just reuse the existing `AssignmentCell` and `TaskCell` classes?

**Comment by lucaspopp0** [comment]
Oh also instead of using a box for the section headers, you can use `ListSubheader` and `dateUtils.humanReadableDate` for a cleaner look

**Comment by beasterbro** [comment]
> Oh also instead of using a box for the section headers, you can use Material UI's `ListSubheader` and `dateUtils.humanReadableDate` for a cleaner look

I was originally using that but thought that on a schedule view the information is more pertinent. I plan to find a more aesthetic way of making this information more easily available at a glance

**Comment by beasterbro** [comment]
> Why not just reuse the existing `AssignmentCell` and `TaskCell` classes?

Originally I was planning to but quickly realized that using them outside of their respective pages without any functionality would require either a big edit of the respective cells or, a similar implementation without the functionality.

**Comment by lucaspopp0** [comment]
> > Why not just reuse the existing `AssignmentCell` and `TaskCell` classes?
> 
> Originally I was planning to but quickly realized that using them outside of their respective pages without any functionality would require either a big edit of the respective cells or, a similar implementation without the functionality.

Hmmm... I feel like it'd be better to add props to disable functionality or something than reimplement the cells

**Review by lucaspopp0 — APPROVED** [review]

**Pull request merged**
