### PR TITLE
Add better sorting for tasks and assignments

### PR DESCRIPTION
**Pull request by lucaspopp0**
- Hide past assignments with a toggle
- Separate sorting for complete/past tasks/assignments
- Add `completionDate` to tasks, and sort by that when completed instead of dueDate

### CODE REVIEW

**Review by beasterbro — DISMISSED** [review]

**Review by beasterbro — CHANGES_REQUESTED** [review]
It looks like when you have a past assignment and update its due date from being a past date to something like "asap" it disappears from both past and current assignments but is still stored in the backend

**Comment by lucaspopp0** [comment]
@beasterbro This makes it so assignments can only be due on a specific date, not ASAP/eventually (cuz when would that even happen anyway)

**Review by beasterbro — CHANGES_REQUESTED** [review]
Can we remove those options then so we can avoid creating unreachable data in the tables?

**Review by prao3 — APPROVED** [review]
seems good to me

**Pull request merged**
