### PR TITLE
404 page

### PR DESCRIPTION
**Pull request by jzassick**
added 404 page with styling so its not ugly

### CODE REVIEW

**Review by lucaspopp0 — APPROVED** [review]
Doesn't really look consistent with the rest of the project, but otherwise looks fine to me

**Comment by jzassick** [comment]
> Doesn't really look consistent with the rest of the project, but otherwise looks fine to me

It can be changed if you guys have something particular in mind.

**Comment by lucaspopp0** [comment]
> > Doesn't really look consistent with the rest of the project, but otherwise looks fine to me
> 
> It can be changed if you guys have something particular in mind. Ill change it to the same colors.

@jzassick up to you. Approved if you don't think it's worth it, but if you wanna update em just lmk and I'll reapprove

**Comment by jzassick** [comment]
@lucaspopp0 changed the colors to white + dark cyan

**Review by lucaspopp0 — APPROVED** [review]

**Pull request merged**
